export enum ElementIds {
  ProfileTable = 'cProfileTableContainer',
  ProfileForm = 'cProfileForm',
  ProfileFormType = 'cProfileFormType',
  ProfileSubmit = 'cProfileFormSubmit',
  ProfileDelete = 'cProfileFormDelete',
  UserTable = 'cUserTableContainer',
  UserForm = 'cUserForm',
  HeaderUser = 'cHeaderUser',
  LoginForm = 'cLoginForm',
  LoginSubmit = 'cLoginSubmit',
  SignupForm = 'cSignupForm',
  SignupSubmit = 'cSignupSubmit',
  DateCarouselSlide = 'cDateCarouselSlide',
  MonthCarouselSlide = 'cMonthCarouselSlide',
  TimesheetTable = 'cTimesheetTableContainer',
  TimesheetForm = 'cTimesheetForm',
  TimesheetSubmit = 'cTimesheetFormSubmit',
  TimesheetDelete = 'cTimesheetFormDelete',
}
