export enum ElementIds {
  ProfileTable = 'cProfileTableContainer',
  ProfileForm = 'cProfileFormContainer',
  ProfileFormType = 'cProfileFormType',
  ProfileSubmit = 'cProfileFormSubmit',
  ProfileDelete = 'cProfileFormDelete',
  UserTable = 'cUserTableContainer',
  UserForm = 'cUserFormContainer',
  HeaderUser = 'cHeaderUser',
  LoginSubmit = 'cLoginSubmit',
  SignupSubmit = 'cSignupSubmit',
  DateCarouselSlide = 'cDateCarouselSlide',
  MonthCarouselSlide = 'cMonthCarouselSlide',
  TimesheetTable = 'cTimesheetTableContainer',
  TimesheetForm = 'cTimesheetFormContainer',
  TimesheetSubmit = 'cTimesheetFormSubmit',
  TimesheetDelete = 'cTimesheetFormDelete',
}
