export enum Icons {
  Add = 'add',
  Close = 'close',
  Edit = 'edit',
  Delete = 'delete',
  Check = 'check',
  Search = 'search',
  ArrowBack = 'arrow_back',
  ArrowForward = 'arrow_forward',
  Menu = 'menu',
  Home = 'home',
  Info = 'info',
  Warning = 'warning',
  Error = 'error',
  AccountCircle = 'account_circle',
  Lock = 'lock',
  Email = 'email',
  Phone = 'phone',
  Star = 'star',
  Favorite = 'favorite',
  ShoppingCart = 'shopping_cart',
  Payment = 'payment',
  Receipt = 'receipt',
  Settings = 'settings',
  ContentCopy = 'content_copy',
  PageView = 'pageview',
  CalendarToday = 'calendar_today',
}
